#!/bin/sh

#PBS -N ivyBridge_MPI_ETH
#PBS -l walltime=02:30:00
#PBS -q mei

#PBS -m abe
#PBS -M carlos.sa01@gmail.com

#PBS -l nodes=2:r641:ppn=32

read -r node_info<$PBS_NODEFILE

echo "Allocated computing node: $node_info"

cd ~/ESC_TP1/NPB3.3.1/NPB3.3-MPI

module purge
module load intel/2013.1.117
module load intel/openmpi_eth/1.8.2
ompi_info --param mpi all

sh scripts/script_ivy_bridge_eth.sh
