#!/bin/sh

#PBS -N nehalem_OMP
#PBS -l walltime=02:30:00
#PBS -q mei

#PBS -m abe
#PBS -M carlos.sa01@gmail.com

#PBS -l nodes=1:r431:ppn=24

read -r node_info<$PBS_NODEFILE

echo "Allocated computing node: $node_info"

cd ~/ESC_TP1/NPB3.3.1/NPB3.3-OMP

module purge
module load gnu/4.9.3

sh script_nehalem.sh
