#!/bin/sh

#PBS -N nehalem_SER
#PBS -l walltime=02:30:00
#PBS -q mei

#PBS -m abe
#PBS -M carlos.sa01@gmail.com

#PBS -l nodes=1:r431:ppn=24

read -r node_info<$PBS_NODEFILE

echo "Allocated computing node: $node_info"

cd ~/ESC_TP1/NPB3.3.1/NPB3.3-SER

module purge
module load intel/2013.1.117 

sh script.sh
